baseURL = "http://walkccc.github.io/CLRS"
languageCode = "en-US"

title = "Solutions"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

[params]
    editURL = "https://github.com/walkccc/CLRS/edit/master/content/"
    description = "solutions"
    author = "Jay"
    showVisitedLinks = false
    themeVariant = "nippon"
  
[outputs]
    home = ["HTML", "RSS", "JSON"]

[Languages]
    [Languages.en]

[permalinks]
    I = "/:filename/"

weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
    name = "<i class='fa fa-fw fa-github'></i> Github repo"
    identifier = "Jay"
    url = "https://github.com/walkccc/CLRS"
    weight = 10

[[Languages.en.menu.shortcuts]]
    name = "<i class='fa fa-fw fa-bookmark'></i> Jay's Blog"
    identifier = "Jay2"
    url = "https://walkccc.github.io/"
    weight = 20
