site_name: CLRS Solutions
theme:
  name: 'material'

repo_name: walkccc/CLRS
repo_url: https://github.com/walkccc/CLRS

extra_css:
  - 'css/extra.css'

extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - pymdownx.superfences

pages:
  - VI Graph Algorithms:
    - 22 Elementary Graph Algorithms:
      - 22.1 Representations of graphs: Chap22/22.1.md
      - 22.2 Breadth-first search: Chap22/22.2.md
      - 22.3 Depth-first search: Chap22/22.3.md
      - 22.4 Topological sort: Chap22/22.4.md
      - 22.5 Strongly connected components: Chap22/22.5.md
      - Chap 22 Problems:
        - 22-1 Classifying edges by breadth-first search: Chap22/Problems/22-1.md
        - 22-2 Articulation points, bridges, and biconnected components: Chap22/Problems/22-2.md
        - 22-3 Euler tour: Chap22/Problems/22-3.md
        - 22-4 Reachability: Chap22/Problems/22-4.md
    - 23 Minimum Spanning Trees:
      - 23.1 Growing a minimum spanning tree: Chap23/23.1.md
      - 23.2 The algorithms of Kruskal and Prim: Chap23/23.2.md
      - Chap 23 Problems:
        - 23-1 Second-best minimum spanning tree: Chap23/Problems/23-1.md
        - 23-2 Minimum spanning tree in sparse graphs: Chap23/Problems/23-2.md
        - 23-3 Bottleneck spanning tree: Chap23/Problems/23-3.md
        - 23-4 Alternative minimum-spanning-tree algorithms: Chap23/Problems/23-4.md
    - 24 Single-Source Shortest Paths:
      - 24.1 The Bellman-Ford algorithm: Chap24/24.1.md
      - 24.2 Single-source shortest paths in directed acyclic graphs: Chap24/24.2.md
      - 24.3 Dijkstra's algorithm: Chap24/24.3.md
      - 24.4 Difference constraints and shortest paths: Chap24/24.4.md
      - 24.5 Proofs of shortest-paths properties: Chap24/24.5.md
      - Chap 24 Problems:
        - 24-1 Yen's improvement to Bellman-Ford: Chap24/Problems/24-1.md
        - 24-2 Nesting boxes: Chap24/Problems/24-2.md
        - 24-3 Arbitrage: Chap24/Problems/24-3.md
        - 24-4 Gabow's scaling algorithm for single-source shortest paths: Chap24/Problems/24-4.md
        - 24-5 Karp's minimum mean-weight cycle algorithm: Chap24/Problems/24-5.md
        - 24-6 Bitonic shortest paths: Chap24/Problems/24-6.md
    - 25 All-Pairs Shortest Paths:
      - 25.1 Shortest paths and matrix multiplication: Chap25/25.1.md
      - 25.2 The Floyd-Warshall algorithm: Chap25/25.2.md
      - 25.3 Johnson's algorithm for sparse graphs: Chap25/25.3.md
      - Chap 25 Problems:
        - 25-1 Transitive closure of a dynamic graph: Chap25/Problems/25-1.md
        - 25-2 Shortest paths in epsilon-dense graphs: Chap25/Problems/25-2.md
    - 26 Maximum Flow:
      - 26.1 Flow networks: Chap26/26.1.md
      - 26.2 The Ford-Fulkerson method: Chap26/26.2.md
      - 26.3 Maximum bipartite matching: Chap26/26.3.md
      - 26.4 Push-relabel algorithms: Chap26/26.4.md
      - 26.5 The relabel-to-front algorithm: Chap26/26.5.md
      - Chap 26 Problems:
        - 26-1 Escape problem: Chap26/Problems/26-1.md
        - 26-2 Minimum path cover: Chap26/Problems/26-2.md
        - 26-3 Algorithmic consulting: Chap26/Problems/26-3.md
        - 26-4 Updating maximum flow: Chap26/Problems/26-4.md
        - 26-5 Maximum flow by scaling: Chap26/Problems/26-5.md
        - 26-6 The Hopcroft-Karp bipartite matching algorithm: Chap26/Problems/26-6.md